/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import javax.swing.JOptionPane;
/**
 *
 * @author hdomingu2
 */
public class Principal extends javax.swing.JFrame {
int l;
        String contra;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdCambiarC.setEnabled(false);
            cmdSeguridad.setEnabled(false);
            cmdSeguridad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdSeguridad = new javax.swing.JButton();
        cmdCambiarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Ejercicio Cuatro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        cmdSeguridad.setText("Seguridad");
        cmdSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeguridadActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        cmdCambiarC.setText("Cambiar Contraseña");
        cmdCambiarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarCActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCambiarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 250, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(543, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
      Password clave;
         Password passwor2;   
         String passwor;
            passwor = txtContrasena.getText();
            passwor2 = new Password(l, passwor);
            passwor2.setLongitud(l);  
    if  (txtContrasena.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Su Contraseña Por Favor",
             "error", JOptionPane.ERROR_MESSAGE);
            txtContrasena.requestFocusInWindow();
        }else {
            contra = txtContrasena.getText();
            l = contra.length();           
            clave = new Password(l, contra);
            JOptionPane.showMessageDialog(this, "Su Contraseña Ha Sido guardada");           
            cmdCambiarC.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdBorrar.setEnabled(true);
            cmdGuardar.setEnabled(false);
            txtContrasena.setEditable(false);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
         txtContrasena.setText("");
        txtArea.setText("");
        cmdGuardar.setEnabled(true);
        cmdCambiarC.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdBorrar.setEnabled(false);
        txtContrasena.setEditable(true);
        txtContrasena.requestFocusInWindow();
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCambiarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarCActionPerformed
        cmdGuardar.setEnabled(true);
       txtContrasena.setEditable(true);
        txtContrasena.selectAll();
        txtContrasena.requestFocusInWindow();
        cmdSeguridad.setEnabled(false);
        cmdCambiarC.setEnabled(false);
        cmdSeguridad.setEnabled(false); 
    }//GEN-LAST:event_cmdCambiarCActionPerformed

    private void cmdSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeguridadActionPerformed
        String con;
        Password cla;
        contra = txtContrasena.getText();
        l= contra.length();
        cla = new Password(l, contra);
        con = cla.fuerte();
        txtArea.setText(con);
    }//GEN-LAST:event_cmdSeguridadActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       Password pass, con;

        contra = txtContrasena.getText();
        l = contra.length();
        pass = new Password(l, contra);
        con = pass.ver();
        txtArea.setText("Su contraseña es: " + con.getContrasena()+ 
         "\n" + " La longitud de su contraseña es: " + con.getContrasena().length());
    }//GEN-LAST:event_cmdMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCambiarC;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
